import { Link, useNavigate } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import api from '../api/axiosClient'
import { useToast } from '../context/ToastContext'
import { useAuth } from '../context/AuthContext'

const EMPTY = []
function scoreLabel(score) { if (score == null) return { text: 'Not matched yet', cls: 'badge' }; if (score >= 80) return { text: 'Strong Match', cls: 'badge badge-success' }; if (score >= 60) return { text: 'Good Match', cls: 'badge badge-warning' }; return { text: 'Weak Match', cls: 'badge badge-danger' } }
function SkillBadges({ values = EMPTY, cls = 'badge' }) { return values.length ? values.slice(0, 8).map(s => <span key={s} className={cls} style={{marginRight:4,marginTop:4}}>{s}</span>) : <span className="muted">No skills detected</span> }
function MatchDetail({ match }) { if (!match) return <span className="badge">Recruiter has not run matching yet</span>; const label = scoreLabel(match.overall_score); return <div className="match-detail"><div><b>{Math.round(match.overall_score)}%</b> <span className={label.cls}>{label.text}</span></div><div className="muted">Skill {Math.round(match.skill_score || 0)}/40 - Experience {Math.round(match.experience_score || 0)}/20 - Location {Math.round(match.location_score || 0)}/10 - Text {Math.round(match.similarity_score || 0)}/30</div><div className="muted">{match.experience_match ? 'Experience matched' : 'Experience gap'} - {match.location_match ? 'Location matched' : 'Location not matched'}</div><div><SkillBadges values={match.matched_skills || []} cls="badge badge-success" /></div>{(match.missing_skills || []).length > 0 && <div><SkillBadges values={match.missing_skills || []} cls="badge badge-danger" /></div>}</div> }

export default function Applications() {
  const toast=useToast(); const navigate=useNavigate(); const { user } = useAuth()
  const [rows,setRows]=useState([]); const [matches,setMatches]=useState([])
  useEffect(()=>{Promise.all([api.get('/api/applications/my'),api.get('/api/matches/my')]).then(([apps,matchRows])=>{setRows(apps.data);setMatches(matchRows.data)})},[])
  const matchesByApp = useMemo(() => matches.reduce((acc,m) => { acc[`${m.job_id}:${m.cv_id}`] = m; if (!acc[m.job_id] || m.overall_score > acc[m.job_id].overall_score) acc[m.job_id] = m; return acc }, {}), [matches])
  async function openMessage(app) { const participant_id = user?.role === 'recruiter' ? app.candidate_id : app.recruiter_id; try { const r=await api.post('/api/conversations',{participant_id,job_id:app.job_id}); navigate(`/messages?conversation=${r.data.id}`) } catch(e) { toast(e.response?.data?.detail || 'Cannot open conversation','error') } }
  return <section><h1>Applications Management</h1><div className="table-wrap"><table><thead><tr><th>Job</th><th>Candidate / CV</th><th>Status</th><th>Matching Detail</th><th>Actions</th></tr></thead><tbody>{rows.map(a=>{const match=matchesByApp[`${a.job_id}:${a.cv_id}`] || matchesByApp[a.job_id];const detailPath=user?.role==='recruiter'?`/recruiter/jobs/${a.job_id}`:`/candidate/jobs/${a.job_id}`;return <tr key={a.id}><td><b><Link to={detailPath}>{a.job_title || a.job_id}</Link></b><br/><span className="muted">{a.company_name}</span></td><td><b>{a.cv_name || a.candidate_name || a.candidate_id}</b><br/><span className="muted">{a.cv_email || 'No email'} - {a.cv_phone || 'No phone'}</span><br/><span className="muted">{a.cv_filename || 'Current CV'}</span><div><SkillBadges values={a.cv_skills || []} cls="badge badge-success" /></div></td><td><span className="badge">{a.status}</span></td><td><MatchDetail match={match}/></td><td><div className="row-actions"><Link className="btn btn-secondary btn-sm" to={detailPath}>View JD</Link><button type="button" className="btn btn-primary btn-sm" onClick={()=>openMessage(a)}>{user?.role==='recruiter'?'Message candidate':'Message recruiter'}</button></div></td></tr>})}</tbody></table></div></section>
}
